// Generates extension/src/env.ts from .env so the extension can read the key.
// Runs automatically before `npm run build` and `npm run watch`.
// env.ts is gitignored: the key must never be committed.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const ENV_FILE = join(ROOT, ".env");
const OUT_FILE = join(ROOT, "extension", "src", "env.ts");

function readVar(contents: string, name: string): string {
  return (
    contents
      .match(new RegExp(`^\\s*${name}\\s*=\\s*(.*)$`, "m"))?.[1]
      ?.trim()
      .replace(/^["']|["']$/g, "") ?? ""
  );
}

let contents = "";
try {
  contents = readFileSync(ENV_FILE, "utf8");
} catch {
  console.warn("No .env found: copy .env.example to .env and add GEMINI_API_KEY.");
}

const apiKey = process.env.GEMINI_API_KEY?.trim() || readVar(contents, "GEMINI_API_KEY");
const model = process.env.GEMINI_MODEL?.trim() || readVar(contents, "GEMINI_MODEL");

if (!apiKey) {
  console.warn("GEMINI_API_KEY is empty: Gemini calls will fail until you set it.");
}

writeFileSync(
  OUT_FILE,
  `// Generated by scripts/writeEnv.mts from .env. Do not edit, do not commit.
export const GEMINI_API_KEY = ${JSON.stringify(apiKey)};
export const GEMINI_MODEL = ${JSON.stringify(model)};
`,
);